buildConfiguration:
  buildCommand: npm run build
  installDependenciesStep:
    command: npm install
    requiredFiles:
      - package.json
      - package-lock.json
      - .npmrc
livePreviewConfiguration:
  setupCommand: ""
  serveCommand: "npm run dev -- --port 8080"
serving:
  reverseProxyPrefix: wondrous-belekoy-b6f5eb.netlify.app/subdirectory

siteStream:
  id: my-site-stream
  fields:
    - id
    - meta
    - name
    - logo
  localization:
    locales:
      - en
    primary: false
  entityId: turtlehead-tacos-site
